Introduction:

World Health Organization has estimated 12 million deaths occur worldwide, every year due to Heart diseases. Half the deaths in the United States and other developed countries are due to cardio vascular diseases. The early prognosis of cardiovascular diseases can aid in making decisions on lifestyle changes in high risk patients and in turn reduce the complications. This research intends to pinpoint the most relevant/risk factors of heart disease as well as predict the overall risk using logistic regression
Data Preparation

Task:

The task is to predict whether patient have 10 year risk of coronary heart disease CHD or not. Additionally, participants also asked to create some data visualization about the data to gained actionable insight about the topic

In [ ]:
https://www.kaggle.com/christofel04/cardiovascular-study-dataset-predict-heart-disea

In [1]:
#importing the packages

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#importing libraries for model validation
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
#importing libraries for metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn import metrics

In [1]:
#importing the dataset
os.chdir("C:\\Users\\User\\Desktop\\Python\\Cardiovascular_logistic")
os.getcwd()

NameError: name 'os' is not defined

In [13]:
df_train=pd.read_csv("train.csv")

In [14]:
df_train.head()

,id,age,education,sex,is_smoking,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,0,64,2.0,F,YES,3.0,0.0,0,0,0,221.0,148.0,85.0,NaN,90.0,80.0,1
1,1,36,4.0,M,NO,0.0,0.0,0,1,0,212.0,168.0,98.0,29.77,72.0,75.0,0
2,2,46,1.0,F,YES,10.0,0.0,0,0,0,250.0,116.0,71.0,20.35,88.0,94.0,0
3,3,50,1.0,M,YES,20.0,0.0,0,1,0,233.0,158.0,88.0,28.26,68.0,94.0,1
4,4,64,1.0,F,YES,30.0,0.0,0,0,0,241.0,136.5,85.0,26.42,70.0,77.0,0

In [18]:
#No.of Males and Females
df_train.sex.value_counts()

F    1923
M    1467
Name: sex, dtype: int64

In [19]:
#No.of People smoking out of 3390
df_train.is_smoking.value_counts()

NO     1703
YES    1687
Name: is_smoking, dtype: int64

In [25]:
#checking for missing values
df_train.isnull().sum()

id                   0
age                  0
education           87
sex                  0
is_smoking           0
cigsPerDay          22
BPMeds              44
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             38
sysBP                0
diaBP                0
BMI                 14
heartRate            1
glucose            304
TenYearCHD           0
dtype: int64

In [42]:
#Removing non significant var
df_train=df_train.drop(['id','education'],axis=1)

In [43]:
df_train.head(8)

,age,sex,is_smoking,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,64,F,YES,3.0,0.0,0,0,0,221.0,148.0,85.0,NaN,90.0,80.0,1
1,36,M,NO,0.0,0.0,0,1,0,212.0,168.0,98.0,29.77,72.0,75.0,0
2,46,F,YES,10.0,0.0,0,0,0,250.0,116.0,71.0,20.35,88.0,94.0,0
3,50,M,YES,20.0,0.0,0,1,0,233.0,158.0,88.0,28.26,68.0,94.0,1
4,64,F,YES,30.0,0.0,0,0,0,241.0,136.5,85.0,26.42,70.0,77.0,0
5,61,F,NO,0.0,0.0,0,1,0,272.0,182.0,121.0,32.80,85.0,65.0,1
6,61,M,NO,0.0,0.0,0,1,0,238.0,232.0,136.0,24.83,75.0,79.0,0
7,36,M,YES,35.0,0.0,0,0,0,295.0,102.0,68.0,28.15,60.0,63.0,0

In [45]:
#mode for cat var
df_train.groupby(['BPMeds']).size()

#max value: 0=>3246

BPMeds
0.0    3246
1.0     100
dtype: int64

In [47]:
#filling with mode for Cat Var
df_train['BPMeds']=df_train['BPMeds'].fillna(0.0)

In [54]:
#imputing the missing values manually with mean

df_train['cigsPerDay']=df_train['cigsPerDay'].fillna(df_train['cigsPerDay'].mean())
df_train['BMI']=df_train['BMI'].fillna(df_train['BMI'].mean())
df_train['heartRate']=df_train['heartRate'].fillna(df_train['heartRate'].mean())
df_train['glucose']=df_train['glucose'].fillna(df_train['glucose'].mean())
df_train['totChol']=df_train['totChol'].fillna(df_train['totChol'].mean())

In [55]:
#checking for missing values
df_train.isnull().sum()

age                0
sex                0
is_smoking         0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [56]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3390 entries, 0 to 3389
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              3390 non-null   int64
 1   sex              3390 non-null   object
 2   is_smoking       3390 non-null   object
 3   cigsPerDay       3390 non-null   float64
 4   BPMeds           3390 non-null   float64
 5   prevalentStroke  3390 non-null   int64
 6   prevalentHyp     3390 non-null   int64
 7   diabetes         3390 non-null   int64
 8   totChol          3390 non-null   float64
 9   sysBP            3390 non-null   float64
 10  diaBP            3390 non-null   float64
 11  BMI              3390 non-null   float64
 12  heartRate        3390 non-null   float64
 13  glucose          3390 non-null   float64
 14  TenYearCHD       3390 non-null   int64
dtypes: float64(8), int64(5), object(2)
memory usage: 397.4+ KB

In [59]:
#Encoding 
df_train_dummied=pd.get_dummies(df_train,columns=['sex'])

In [60]:
df_train_dummied

,age,is_smoking,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD,sex_F,sex_M
0,64,YES,3.0,0.0,0,0,0,221.0,148.0,85.0,25.794964,90.0,80.0,1,1,0
1,36,NO,0.0,0.0,0,1,0,212.0,168.0,98.0,29.770000,72.0,75.0,0,0,1
2,46,YES,10.0,0.0,0,0,0,250.0,116.0,71.0,20.350000,88.0,94.0,0,1,0
3,50,YES,20.0,0.0,0,1,0,233.0,158.0,88.0,28.260000,68.0,94.0,1,0,1
4,64,YES,30.0,0.0,0,0,0,241.0,136.5,85.0,26.420000,70.0,77.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3385,60,NO,0.0,0.0,0,0,0,261.0,123.5,79.0,29.280000,70.0,103.0,0,1,0
3386,46,NO,0.0,0.0,0,0,0,199.0,102.0,56.0,21.960000,80.0,84.0,0,1,0
3387,44,YES,3.0,0.0,0,1,0,352.0,164.0,119.0,28.920000,73.0,72.0,1,0,1
3388,60,NO,0.0,0.0,0,1,0,191.0,167.0,105.0,23.010000,80.0,85.0,0,0,1
3389,54,NO,0.0,0.0,0,0,0,288.0,124.0,77.0,29.880000,79.0,92.0,0,1,0

In [63]:
df_train_dummied=pd.get_dummies(df_train_dummied,columns=['is_smoking'])

In [65]:
df_train_dummied.head()

,age,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD,sex_F,sex_M,is_smoking_NO,is_smoking_YES
0,64,3.0,0.0,0,0,0,221.0,148.0,85.0,25.794964,90.0,80.0,1,1,0,0,1
1,36,0.0,0.0,0,1,0,212.0,168.0,98.0,29.770000,72.0,75.0,0,0,1,1,0
2,46,10.0,0.0,0,0,0,250.0,116.0,71.0,20.350000,88.0,94.0,0,1,0,0,1
3,50,20.0,0.0,0,1,0,233.0,158.0,88.0,28.260000,68.0,94.0,1,0,1,0,1
4,64,30.0,0.0,0,0,0,241.0,136.5,85.0,26.420000,70.0,77.0,0,1,0,0,1

In [76]:
#removing first dummy
used_features=['age', 'cigsPerDay', 'BPMeds', 'prevalentStroke', 'prevalentHyp',
               'diabetes', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate','sex_M', 'is_smoking_YES']

In [77]:
#Indep Variable and Target Variable
x=df_train_dummied[used_features].values
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,64.0,3.0,0.0,0.0,0.0,0.0,221.0,148.0,85.0,25.794964,90.0,0.0,1.0
1,36.0,0.0,0.0,0.0,1.0,0.0,212.0,168.0,98.0,29.770000,72.0,1.0,0.0
2,46.0,10.0,0.0,0.0,0.0,0.0,250.0,116.0,71.0,20.350000,88.0,0.0,1.0
3,50.0,20.0,0.0,0.0,1.0,0.0,233.0,158.0,88.0,28.260000,68.0,1.0,1.0
4,64.0,30.0,0.0,0.0,0.0,0.0,241.0,136.5,85.0,26.420000,70.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3385,60.0,0.0,0.0,0.0,0.0,0.0,261.0,123.5,79.0,29.280000,70.0,0.0,0.0
3386,46.0,0.0,0.0,0.0,0.0,0.0,199.0,102.0,56.0,21.960000,80.0,0.0,0.0
3387,44.0,3.0,0.0,0.0,1.0,0.0,352.0,164.0,119.0,28.920000,73.0,1.0,1.0
3388,60.0,0.0,0.0,0.0,1.0,0.0,191.0,167.0,105.0,23.010000,80.0,1.0,0.0
3389,54.0,0.0,0.0,0.0,0.0,0.0,288.0,124.0,77.0,29.880000,79.0,0.0,0.0

In [78]:
y=df_train_dummied['TenYearCHD'].values
pd.DataFrame(y)

      0
0     1
1     0
2     0
3     1
4     0
...  ..
3385  0
3386  0
3387  1
3388  0
3389  0

[3390 rows x 1 columns]

In [122]:
#train and test data split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=150)

In [123]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2542, 13)
(848, 13)
(2542,)
(848,)

In [124]:
#Model Building
logi_model=LogisticRegression()
logi_model.fit(x_train,y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [125]:
#predicted
y_pred=logi_model.predict(x_test)

In [126]:
#confusion Matrix
metrics.confusion_matrix(y_test,y_pred)

array([[719,   2],
       [122,   5]], dtype=int64)

In [127]:
metrics.accuracy_score(y_test,y_pred)

0.8537735849056604

In [ ]:
#ACCURACY=85%

In [128]:
#cross validation
from sklearn.model_selection import cross_val_score
accuracy=cross_val_score(estimator=logi_model, X=x_train, y= y_train, cv=15)

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [129]:
accuracy

array([0.84705882, 0.84705882, 0.85294118, 0.84117647, 0.85294118,
       0.84117647, 0.84705882, 0.85798817, 0.84615385, 0.85798817,
       0.84023669, 0.85798817, 0.86982249, 0.85207101, 0.85207101])

In [130]:
accuracy.mean()

0.8509154194222067

In [ ]:
from sklearn.model_selection import cross_val_score
accuracy=cross_val_score(estimator=logi_model, X=x_test, y= y_test, cv=15)